version: '3.8'

services:
  # Backend - FastAPI CrewAI Server
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: venturebots-backend
    container_name: venturebots-backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend - React/Vite SPA
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      args:
        VITE_BACKEND_URL: ${VENTUREBOT_API_URL:-http://backend:8000}
    image: venturebots-frontend
    container_name: venturebots-app
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 
